### ISSUE TITLE
Text in field for Authenticated Users is displayed to unauthenticated users

### ISSUE THREAD

**Issue by cborn** [dbnschools/moodle-theme_learnr#11]
Moodle 4.0.1+ Build 20220624

When I put text in the field labeled "For authenticated users", this content is displayed even when someone is not authenticated.
<img width="1422" alt="Screen Shot 2022-06-30 at 9 39 30 AM" src="https://user-images.githubusercontent.com/1149264/176706026-4d444fcc-57b4-49b4-b1a6-7c5815c4198c.png">

**Comment by dbnschools** [comment]
Completely new notice system in latest release.
