### ISSUE TITLE
Dropdown menu is arranged behind the Block Drawer

### ISSUE THREAD

**Issue by i11info** [dbnschools/moodle-theme_learnr#13]
- In LearnR theme settings enable: Show Block Drawer
- Open the sidebar
- Click on profile picture
- The dropdown menu is arranged behind the Block Drawer
- Expected to be on top of Block Drawer

In the default Boost theme there is no such error
![learnr](https://user-images.githubusercontent.com/22219330/176921588-a81b97b8-f91a-4846-8208-b005ec41fcb6.jpg)
![boost](https://user-images.githubusercontent.com/22219330/176921602-ad3a9120-b084-4ec1-810f-5e7c31da393f.png)

**Comment by dbnschools** [comment]
Should be fixed in latest release.
