### ISSUE TITLE
Search Course dropdown box options

### ISSUE THREAD

**Issue by jtyronian** [dbnschools/moodle-theme_learnr#15]
I was wondering if the search courses function can be tweaked in settings to have or not have the dropdown box as to 'where' within the site you are searching so it can be turned on or off. 

![Screenshot 2022-07-10 162105](https://user-images.githubusercontent.com/77734384/178133841-9db7fc06-f3cf-414c-bb01-8a4b92a14593.png)

**Comment by dbnschools** [comment]
That would be a function of core Moodle and not the theme.
