### ISSUE TITLE
Category expand/collapse

### ISSUE THREAD

**Issue by jtyronian** [dbnschools/moodle-theme_learnr#16]
Would it be possible to have it so an admin can choose to have the categories expand or not as a on/off option.  For our site and using Fordson, our top category page is listings of 'Institutes' but its not expandable and thus doesn't allow them to show the colleges or courses under until the click on one and it takes them to that category page.

**Comment by dbnschools** [comment]
Not at this time.  That is a feature of Moodle and not the theme.
