### ISSUE TITLE
Copied code credit

### ISSUE THREAD

**Issue by gjb2048** [dbnschools/moodle-theme_learnr#2]
Dear Chris,

RE: https://moodle.org/mod/forum/discuss.php?d=433845#p1745684

This is the commit https://github.com/gjb2048/moodle-theme_essential/commit/8650738efca29c3ce2a4f997dfbe19e2d76dd89a where you can see what code I wrote that you've used and in places, adapted.

Kind regards,

Gareth

**Comment by dbnschools** [comment]
Does the following notice meet requirements?
https://github.com/dbnschools/moodle-theme_learnr/blob/main/classes/output/core_renderer.php#L359-L366

**Comment by gjb2048** [comment]
@dbnschools I'm not sure, you'll need to check with Dan please as he raised it as an issue.

**Comment by dbnschools** [comment]
@gjb2048 I messaged him on moodle.org.

**Comment by mudrd8mz** [comment]
IMHO, putting inline comments such as https://github.com/dbnschools/moodle-theme_learnr/blob/fee53c21c9f50ee6fa60be95ab131fcd049b61f6/classes/output/core_renderer.php#L358 is nice, but also impractical and overkill in any open-source project.

I believe it would be enough if such credits were given in the README file, in a general way. I don't think anyone would expect that you would comment the origin on every single line you copied over from / were inspired by etc.
