### ISSUE TITLE
NavBar My courses as dropdown

### ISSUE THREAD

**Issue by jolly-jump** [dbnschools/moodle-theme_learnr#20]
I see you have implemented the drop down within the course.

Is it also possible to replace "My courses" in the main NavBar by a "My courses" drop-down menu (as it was in the Fordson theme).
I think this corresponds to your philosophy to provide very easy structured navigation. 
I even think it would be more logical to put it up there than within the course.

Let me know, if I am unclear of what I mean.
Thank you.

**Comment by dbnschools** [comment]
We've decided to keep the my courses main menu and elected to have a "Recent Courses" drop down just above the course title.
