### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by jolly-jump** [dbnschools/moodle-theme_learnr#21]
Hi again, 

I can see that you do not want to clutter the experience with unnecessary navigational things.
What I do not understand is your option "theme_learnr | showblockdrawer", since it basically does nothing in my case in either checkbox variant.  I never see any navigational drawer, only the drawer with the course index as soon as I am in a course with usual theme format.
Is there some other environment that I have to be aware to see any change?

My version: theme_learnr v1.7 2022052400
Moodle: Moodle 4.0.2 (Build: 20220711)

Thank you for your help!

**Comment by dbnschools** [comment]
It has been fixed in the latest release.  It will show/hide the drawers on pages.
