### ISSUE TITLE
Home Page Alert Shows Up Before Long In - and unfortunately after log in too

### ISSUE THREAD

**Issue by strable** [dbnschools/moodle-theme_learnr#22]
In the Content Areas of the admin control, there are two boxes for adding messages to the "Home Page" before log in - and another after "log in".   Unfortunately, the same message in the Homepage Alert shows up when logged in as well. The reverse happens as well. Adding a note in the "Homepage Textbox Authenticated User" shows up on the "Home Page"

<img width="1048" alt="Home Page Alerts" src="https://user-images.githubusercontent.com/61529586/187008984-f430d8d2-c275-4609-b3f0-8fd47db57839.png">

**Comment by dbnschools** [comment]
This has been changed in the most recent release.
