### ISSUE TITLE
Feature Request: Filters available in menus and footer

### ISSUE THREAD

**Issue by Bjoern-Ge** [dbnschools/moodle-theme_learnr#26]
Hi Chris,
it would be really nice to have the possibility to use filters in menus and footer.
I found this https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/README.md#filtercodes-in-custom-menus explanation about it.
But I was unsure where to add it exactly in the learnr theme.
Thanks

**Comment by Richardvi** [comment]
Yep, also for filtercodes this would be really great to have!

**Comment by dbnschools** [comment]
.custom-control-input:checked ~ .custom-control-label::before {
    color: #fff;
    border-color: #78ff9b!important;
    background-color: #78ff9b !important;
}
