### ISSUE TITLE
Marketing Blocks will not appear in Moodle 4.1.1  

### ISSUE THREAD

**Issue by ecottis** [dbnschools/moodle-theme_learnr#28]
For some reason non of the marketing blocks seem to work.

Can you please review

**Comment by bilo1967** [comment]
Same for me with  v4.2.r7 on Moodle 4.1.2.
Maybe it's me not doing something or doing something wrong, but I've not been able to display advertisement tiles.

(Note: Advertisement Tiles do work with Boost Union in the same setup)

**Comment by bilo1967** [comment]
Ok. found it. I've made a pull request with the fix.
The problem is in strpos needles in layout/drawers.php from line 169 to 186 (just need to quote the values).
```php
// DBN Update begin.
// Include the template content for the advertisement tiles, but only if we are on the frontpage.
if ((strpos($this->page->theme->settings->showadvertonpages, "1") !== false) && $PAGE->pagelayout == 'frontpage') {
    require_once(__DIR__ . '/includes/advertisementtiles.php');
}

if ((strpos($this->page->theme->settings->showadvertonpages, "2") !== false) && $PAGE->pagelayout == 'mydashboard') {
    require_once(__DIR__ . '/includes/advertisementtiles.php');
}

if ((strpos($this->page->theme->settings->showadvertonpages, "3") !== false) && $PAGE->pagelayout == 'mycourses') {
    require_once(__DIR__ . '/includes/advertisementtiles.php');
}

if ((strpos($this->page->theme->settings->showadvertonpages, "4") !== false) && $PAGE->pagelayout == 'course') {
    require_once(__DIR__ . '/includes/advertisementtiles.php');
}
// DBN Update end.
```

**Comment by dbnschools** [comment]
Thank you!  I will have this in the new update.

**Comment by bilo1967** [comment]
Thank you for the theme!
Glad to help when I can.

Il giorno mer 19 lug 2023 alle ore 14:40 Dearborn Public Schools <
***@***.***> ha scritto:
