### ISSUE TITLE
Deprecation/missing string/other PHP errors running on Moodle 4.1.2 (Build: 20230313)

### ISSUE THREAD

**Issue by logan-reynolds** [dbnschools/moodle-theme_learnr#30]
Getting the following errors consistently on various pages (Homepage, Dashboard, My Courses page, etc.) when installing and trying to run the latest theme_learnr version 2023050507 on Moodle 4.1.2 (Build: 20230313), which prevents various display elements such as course listing on the Homepage:
```
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/html/theme/learnr/layout/drawers.php on line 171

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/html/theme/learnr/layout/drawers.php on line 175

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/html/theme/learnr/layout/drawers.php on line 179

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/html/theme/learnr/layout/drawers.php on line 183
Invalid get_string() identifier: 'pluginname' or component 'local_bulkenrol'. Perhaps you are missing $string['pluginname'] = ''; in /lang/en/local_bulkenrol.php?

    line 356 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7409 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 979 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
    line 350 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 88 of /var/www/moodledata/localcache/mustache/1685472253/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
    line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
    line 1477 of /lib/outputrenderers.php: call to include()
    line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 116 of /index.php: call to core_renderer->header()

Notice: Undefined property: stdClass::$coursetilestyle in /var/www/html/theme/learnr/classes/output/core/course_renderer.php on line 59

Notice: Undefined property: stdClass::$coursetilestyle in /var/www/html/theme/learnr/classes/output/core/course_renderer.php on line 50
```

**Comment by dbnschools** [comment]
When upgrading did you set the Course Style option?  Please go to that page in Theme settings and save an option to see if the error goes away.

**Comment by mladwig** [comment]
Logan, did deschools solution solve the issue? We are looking to use this theme for our Moodle.

**Comment by dbnschools** [comment]
I am not sure on Moodle 4.1.2 but I do not get any error messages on Moodle 4.2

**Comment by ghost** [comment]
In checking the 'coursetilestyle' setting's value it is already showing as "Tile Style One" when I visit the settings page, which I doublechecked previously during testing.  However when I save on that page that single error does go away, which indicates this value isn't being properly set to a default value when the plugin is installed/upgraded and is instead just being displayed at the first option available in the dropdown when no value is set.  So to summarize the fixes needed to resolve these errors would be the following:

- Either include an upgrade step to ensure that a default value is set for the 'coursetilestyle' and all other theme settings, or that an option indicating an empty/null value is added to the UI so it's displayed value is accurate.
- Resolve deprecation warnings on strpos() to determine if any required numeric values are going to be negatively affected by interpretation as strings.
- Any dependencies on component local_bulkenrol should be removed, or it should be formally declared as a dependency in version.php if it is required for usage of this plugin.

**Comment by qqtuyen** [comment]
I'm getting them in 4.1.4 with php 8.0.  Do we have an ETA on a fix for this issue ?

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
