### ISSUE TITLE
login background image not scaled to fit window

### ISSUE THREAD

**Issue by ChristopherKingChemist** [dbnschools/moodle-theme_learnr#4]
Nice theme!

I've uploaded a 1920 x 1280 jpg picture to use as the background on the login page.  However, the picture is expanded so that only the top left about 600 x 400 pixels are displayed.  Looks like this picture isn't set to be "responsive" using bootstrap.

Chris King

**Comment by dbnschools** [comment]
I could not replicate this issue.  Maybe send a screen shot or more details.
