### ISSUE TITLE
No define call for theme_learnr/backtotopbutton & Error: No define call for theme_learnr/offcanvas

### ISSUE THREAD

**Issue by balyaapik** [dbnschools/moodle-theme_learnr#42]
I got this error message from my school site :
Error: No define call for theme_learnr/backtotopbutton
http://requirejs.org/docs/errors.html#nodefine
    makeError https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1877
    execCb https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1871
lockdown-install.js:1:93966
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    (Async: EventListener.handleEvent)
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    repairIntrinsics moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    <anonymous> moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-run.js:4
Error: No define call for theme_learnr/offcanvas
http://requirejs.org/docs/errors.html#nodefine
    makeError https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1908
    execCb https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1871
lockdown-install.js:1:93966
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    (Async: EventListener.handleEvent)
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    repairIntrinsics moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    functors moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-install.js:1
    <anonymous> moz-extension://b501533e-9d60-4bf8-9c38-b29d9618f719/lockdown-run.js:4
Error: No define call for theme_learnr/offcanvas
http://requirejs.org/docs/errors.html#nodefine
    makeError https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1908
    execCb https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    emit https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    h https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    completeLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    onScriptLoad https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    load https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    fetch https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    check https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    bind https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    each https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    enable https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    init https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    o https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    requirejs https://siakad.sman1-muntilan.sch.id/lib/javascript.php/1696773392/lib/requirejs/require.min.js:5
    <anonymous> https://siakad.sman1-muntilan.sch.id/admin/search.php:1871
lockdown-install.js:1:93966

Does Anyone has a solution for it?

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
