### ISSUE TITLE
Moodle 4.3 not compatible

### ISSUE THREAD

**Issue by ghost** [dbnschools/moodle-theme_learnr#43]
Hi all.
I hope everybody is ok and healthy.
I just installed learnr theme on a moodle 4.3 instance.
yes, I am a earlier adopter.
anyway. I would like to request a compatible version for moodle 4.3 onwards.
thanks in advance.

**Comment by Richardvi** [comment]
We have upgraded as well. LearnR works for us, but these are the messages we are getting in developer mode:

**user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.**
line 41 of /lib/ajax/ajaxlib.php: call to debugging()
line 58 of /theme/learnr/layout/drawers.php: call to user_preference_allow_ajax_update()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 134 of /admin/settings.php: call to core_renderer->header()
**user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.**
line 41 of /lib/ajax/ajaxlib.php: call to debugging()
line 59 of /theme/learnr/layout/drawers.php: call to user_preference_allow_ajax_update()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 134 of /admin/settings.php: call to core_renderer->header()
**Invalid get_string() identifier: 'pluginname' or component 'local_bulkenrol'. Perhaps you are missing $string['pluginname'] = ''; in /lang/en/local_bulkenrol.php?**
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7516 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 979 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
line 351 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 88 of /home/learndev/moodledata/localcache/mustache/1698248772/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 134 of /admin/settings.php: call to core_renderer->header()
**String [editcoursecompletionsettings,core_completion] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://moodledev.io/general/projects/api/string-deprecation**
line 397 of /lib/classes/string_manager_standard.php: call to debugging()
line 7516 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 1061 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
line 351 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 88 of /home/learndev/moodledata/localcache/mustache/1698248772/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 134 of /admin/settings.php: call to core_renderer->header()

**Comment by Richardvi** [comment]
Sorry, not all messages seem to be from LearnR, but some are.

**Comment by vkadam** [comment]
Getting following errors with Moodle `4.3`, theme version `v4.2.r8 (2023071008)`

```
user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.
line 41 of /lib/ajax/ajaxlib.php: call to debugging()
line 58 of /theme/learnr/layout/drawers.php: call to user_preference_allow_ajax_update()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 119 of /theme/index.php: call to core_renderer->header()

user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.
line 41 of /lib/ajax/ajaxlib.php: call to debugging()
line 59 of /theme/learnr/layout/drawers.php: call to user_preference_allow_ajax_update()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 119 of /theme/index.php: call to core_renderer->header()

Invalid get_string() identifier: 'pluginname' or component 'local_bulkenrol'. Perhaps you are missing $string['pluginname'] = ''; in /lang/en/local_bulkenrol.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7516 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 978 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
line 350 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 88 of data/localcache/mustache/1699481243/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 119 of /theme/index.php: call to core_renderer->header()

String [editcoursecompletionsettings,core_completion] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://moodledev.io/general/projects/api/string-deprecation
line 397 of /lib/classes/string_manager_standard.php: call to debugging()
line 7516 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 1060 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
line 350 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 88 of data/localcache/mustache/1699481243/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 119 of /theme/index.php: call to core_renderer->header()

```

**Comment by Richardvi** [comment]
I think these are the same as ours. Chris is probably busy, but will update dbnschools to Moodle 4.3 sooner or later. Let's be patient :)

**Comment by dbnschools** [comment]
I am currently working on a Moodle 4.3 version and I have corrected many of the issues.

**Comment by Richardvi** [comment]
@dbnschools we still have som errors after our recent upgrade:

[02-Jan-2024 18:22:43 Europe/Amsterdam] Debugging: Exception encountered in event observer '**\theme_learnr\eventobservers::course_updated': Table "theme_learnr_menuitems" does not exist** in 
* line 1462 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 496 of /theme/learnr/smartmenus/menulib.php: call to moodle_database->get_records()
* line 176 of /theme/learnr/classes/eventobservers.php: call to smartmenu_helpers::purge_cache_dynamic_courseitems()
* line ? of unknownfile: call to theme_learnr\eventobservers::course_updated()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 2622 of /course/lib.php: call to core\event\base->trigger()
* line 1214 of /course/externallib.php: call to update_course()
* line 1504 of /webservice/lib.php: call to core_course_external::update_courses()
* line 1350 of /webservice/lib.php: call to webservice_base_server->execute()
* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()

**Comment by Richardvi** [comment]
Even fatal PHP errors unfortunately:

[02-Jan-2024 18:02:08 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to undefined method theme_learnr\output\core_renderer::close_element_for_append() in /home/learn/public_html/lib/classes/shutdown_manager.php:245
Stack trace:
#0 /home/learn/public_html/lib/classes/shutdown_manager.php(182): core_shutdown_manager::request_shutdown()
#1 [internal function]: core_shutdown_manager::shutdown_handler()
#2 {main}
  thrown in /home/learn/public_html/lib/classes/shutdown_manager.php on line 245

**Comment by Richardvi** [comment]
Also I get this from event manager, what exactly is Learnr doing here?

[03-Jan-2024 15:54:07 Europe/Amsterdam] Debugging: Exception encountered in event observer '\theme_learnr\eventobservers::role_assigned': Error reading from database in 
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 259 of /theme/learnr/smartmenus/menulib.php: call to mysqli_native_moodle_database->get_records_sql()
* line 472 of /theme/learnr/smartmenus/menulib.php: call to smartmenu_helpers::find_condition_used_menus()
* line 131 of /theme/learnr/classes/eventobservers.php: call to smartmenu_helpers::purge_cache_session_roles()
* line ? of unknownfile: call to theme_learnr\eventobservers::role_assigned()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 200 of /cohort/lib.php: call to core\event\base->trigger()
* line 712 of /cohort/externallib.php: call to cohort_add_member()
* line 1504 of /webservice/lib.php: call to core_cohort_external::add_cohort_members()
* line 1350 of /webservice/lib.php: call to webservice_base_server->execute()
* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()

**Comment by Richardvi** [comment]
[03-Jan-2024 16:23:03 Europe/Amsterdam] Debugging: Exception encountered in event observer '\theme_learnr\eventobservers::course_updated': Table "theme_learnr_menuitems" does not exist in 
* line 1462 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 496 of /theme/learnr/smartmenus/menulib.php: call to moodle_database->get_records()
* line 176 of /theme/learnr/classes/eventobservers.php: call to smartmenu_helpers::purge_cache_dynamic_courseitems()
* line ? of unknownfile: call to theme_learnr\eventobservers::course_updated()
* line 155 of /lib/classes/event/manager.php: call to call_user_func()
* line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
* line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
* line 2622 of /course/lib.php: call to core\event\base->trigger()
* line 1214 of /course/externallib.php: call to update_course()
* line 1504 of /webservice/lib.php: call to core_course_external::update_courses()
* line 1350 of /webservice/lib.php: call to webservice_base_server->execute()
* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()

**Comment by dbnschools** [comment]
LearnR is now a proper child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.
