### ISSUE TITLE
local_bulkenrol dependent

### ISSUE THREAD

**Issue by balyaapik** [dbnschools/moodle-theme_learnr#44]
The plugins theme needs local_bulkenrol to work properly

invalid get_string() identifier: 'pluginname' or component 'local_bulkenrol'. Perhaps you are missing $string['pluginname'] = ''; in /lang/en/local_bulkenrol.php?

    line 356 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7414 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 978 of /theme/learnr/classes/output/core_renderer.php: call to get_string()
    line 350 of /theme/learnr/classes/output/core_renderer.php: call to theme_learnr\output\core_renderer->coursemanagementdash()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_learnr\output\core_renderer->headerbuttons()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 88 of /var/www/localcache/mustache/1696918769/learnr/__Mustache_d3fc7f63915ec935241c418139b23bf1.php: call to Mustache_Context->findDot()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_d3fc7f63915ec935241c418139b23bf1->renderInternal()
    line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 189 of /theme/learnr/layout/drawers.php: call to renderer_base->render_from_template()
    line 1477 of /lib/outputrenderers.php: call to include()
    line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 134 of /admin/settings.php: call to core_renderer->header()

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
