### ISSUE TITLE
Change marketing tile title to checkbox--feature request

### ISSUE THREAD

**Issue by ChristopherKingChemist** [dbnschools/moodle-theme_learnr#5]
This is a feature request regarding marketing tiles.  Currently, a marketing tile is activated by entering a title for it in a textbox.  I would prefer to activate the marketing tile by clicking a checkbox; the title would be entered in the tile's content area.  The advantage of this is that I can format the title as I please.  Here's a picture showing the title in the title text area and in the tile's content area.
![Screenshot 2022-05-20 114940](https://user-images.githubusercontent.com/34283059/169575298-14919b8e-8eef-4e59-bedb-4bb12de68389.png)
By putting the title in the content area, it can be formatted (centered, bold, with a colored background, in this case).  
The problem with making this change is that it would be awkward for users who are already using this theme.  Perhaps making the change would be OK, since this is still a beta version of the theme.
Chris

**Comment by dbnschools** [comment]
This has been revised in current release and is a new advert tile.
