### ISSUE TITLE
LearnR v 1.6 - Fatal error

### ISSUE THREAD

**Issue by caiadogithub** [dbnschools/moodle-theme_learnr#6]
"Fatal error: Cannot redeclare page_location_incourse_themeconfig() (previously declared in /XXX/XXXX/XXXX/theme/fordson/lib/fordson_lib.php:132) in /XXX/XXXX/XXXX/theme/learnr/lib.php on line 256"

There is a conflict between "Fordson" and "LearnR".

**Comment by dbnschools** [comment]
Fixed in 1.6.1
